In [ ]:
import numpy as np
import json

## random 8 pop para

In [ ]:
pops = np.array([20683, 5834, 21915, 5479, 4850, 1065, 14395, 2948])
pops_prop = np.random.choice([1, -1], size=len(pops)) # 1: excitatory, -1: inhibitory

pconn = np.random.randint(0, 2, (len(pops), len(pops)))
np.fill_diagonal(pconn, 1)

J = np.random.uniform(0.06, 0.3)  # excitatory synaptic weight in mV, w^{αβ} in the paper
g = np.random.uniform(3, 5)   # inhibition-to-excitation ratio, -g*J is the weight for inhibitory signals
J_syn = np.outer(np.ones_like(pops_prop), np.where(pops_prop == -1, -g*J, J))
J_syn = J_syn * pconn * np.random.uniform(0.5, 1.5, (len(pops), len(pops)))

pconn_coeff = np.array([
    [0.1009, 0.1689, 0.0437, 0.0818, 0.0323, 0, 0.0076, 0],
    [0.1346, 0.1371, 0.0316, 0.0515, 0.0755, 0, 0.0042, 0],
    [0.0077, 0.0059, 0.0497, 0.135, 0.0067, 0.0003, 0.0453, 0],
    [0.0691, 0.0029, 0.0794, 0.1597, 0.0033, 0, 0.1057, 0],
    [0.1004, 0.0622, 0.0505, 0.0057, 0.0831, 0.3726, 0.0204, 0],
    [0.0548, 0.0269, 0.0257, 0.0022, 0.06, 0.3158, 0.0086, 0],
    [0.0156, 0.0066, 0.0211, 0.0166, 0.0572, 0.0197, 0.0396, 0.2252],
    [0.0364, 0.001, 0.0034, 0.0005, 0.0277, 0.008, 0.0658, 0.1443]
])
pconn = pconn * pconn_coeff

mu = np.random.uniform(20, 60, len(pops)) # V_rest + I_external * R
tau_m = np.random.uniform(10, 40, len(pops))  # membrane time constant
V_th = np.random.uniform(10, 30, len(pops))  # baseline threshold (non-accumulating part)

tau_sfa_exc = [np.random.uniform(0, 1500)]  # threshold adaptation time constants of excitatory neurons
tau_sfa_inh = [np.random.uniform(0, 1500)]  # threshold adaptation time constants of inhibitory neurons
J_sfa_exc = [np.random.uniform(0, 1500)]   # adaptation strength: size of feedback kernel theta (= area under exponential) in mV*ms
J_sfa_inh = [np.random.uniform(0, 1500)]   # in mV*ms
tau_theta = np.array([tau_sfa_exc if prop == 1 else tau_sfa_inh for prop in pops_prop])
J_theta = np.array([J_sfa_exc if prop == 1 else J_sfa_inh for prop in pops_prop])

In [ ]:
print(J_syn)
print(mu)
print(tau_m)
print(V_th)
print(J_theta)
print(tau_theta)

print("-- -- --")

J_syn_list = J_syn.tolist()
mu_list = mu.tolist()
tau_m_list = tau_m.tolist()
V_th_list = V_th.tolist()
J_theta_list = J_theta.tolist()
tau_theta_list = tau_theta.tolist()

setting = 1
seed_num = 1

# Store your data into a dictionary
data_dict = {"setting": setting, 
        "seed_num": seed_num, 
        "J_syn": J_syn_list, 
        "mu": mu_list, 
        "tau_m": tau_m_list, 
        "V_th": V_th_list, 
        "J_theta": J_theta_list, 
        "tau_theta": tau_theta_list
        }

# Convert the dictionary into a JSON string
json_str = json.dumps(data_dict)

# Create the file name string
filename = f"data_{setting}-{seed_num}.json"

# Write the JSON string to a file
with open(filename, 'w') as json_file:
    json_file.write(json_str)


# Read the JSON string from the file
with open(filename, 'r') as json_file:
    json_str = json_file.read()

# Convert the JSON string into a dictionary
data_dict = json.loads(json_str)

# Convert the nested lists back into numpy arrays
J_syn = np.array(data_dict["J_syn"])
mu = np.array(data_dict["mu"])
tau_m = np.array(data_dict["tau_m"])
V_th = np.array(data_dict["V_th"])
J_theta = np.array(data_dict["J_theta"])
tau_theta = np.array(data_dict["tau_theta"])

print(J_syn)
print(mu)
print(tau_m)
print(V_th)
print(J_theta)
print(tau_theta)

print("-- -- --")

print(f"J_syn shape: {J_syn.shape}")
print(f"mu shape: {mu.shape}")
print(f"tau_m shape: {tau_m.shape}")
print(f"V_th shape: {V_th.shape}")
print(f"J_theta shape: {J_theta.shape}")
print(f"tau_theta shape: {tau_theta.shape}")

print("-- -- --")

print(data_dict)

[[-0.36236029  0.          0.1117798   0.         -0.         -0.20942072
   0.12660862 -0.33623147]
 [-0.24393214  0.09908151  0.18583693  0.18543585 -0.32228401 -0.
   0.16743436 -0.54981025]
 [-0.25017885  0.131471    0.08595532  0.         -0.4454452  -0.
   0.         -0.        ]
 [-0.4806421   0.11158571  0.          0.18082324 -0.         -0.32364397
   0.1259807  -0.46624312]
 [-0.          0.          0.          0.         -0.56653226 -0.
   0.17565134 -0.        ]
 [-0.45345206  0.          0.          0.16783139 -0.         -0.19695945
   0.13562157 -0.45962432]
 [-0.38078575  0.09480242  0.1363738   0.13794772 -0.         -0.38931957
   0.11735037 -0.4043064 ]
 [-0.          0.08222885  0.1487328   0.         -0.54625509 -0.2830505
   0.1872774  -0.19446519]]
[48.60437227 37.57707267 33.0404658  49.35120068 22.05175566 40.58282475
 48.06477502 48.69486097]
[19.93155255 13.86261217 28.85888864 25.51372838 38.44645229 24.65950117
 25.5013078  14.96476037]
[27.46435516 14.54

## random 3 pop para

In [ ]:
pops = np.array([400, 200, 400])
pops_prop = np.random.choice([1, -1], size=len(pops)) # 1: excitatory, -1: inhibitory

pconn = np.random.randint(0, 2, (len(pops), len(pops)))
np.fill_diagonal(pconn, 1)

J = np.random.uniform(0.06, 0.3)  # excitatory synaptic weight in mV, w^{αβ} in the paper
g = np.random.uniform(3, 6)   # inhibition-to-excitation ratio, -g*J is the weight for inhibitory signals
J_syn = np.outer(np.ones_like(pops_prop), np.where(pops_prop == -1, -g*J, J))
J_syn = J_syn * pconn * np.random.uniform(0.5, 1.5, (len(pops), len(pops)))

pconn_coeff = 0.6
pconn = pconn * pconn_coeff

mu = np.random.uniform(20, 60, len(pops)) # V_rest + I_external * R
tau_m = np.random.uniform(10, 40, len(pops))  # membrane time constant
V_th = np.random.uniform(10, 30, len(pops))  # baseline threshold (non-accumulating part)

tau_sfa_exc = [np.random.uniform(80, 1500)]  # threshold adaptation time constants of excitatory neurons
tau_sfa_inh = [np.random.uniform(80, 1500)]  # threshold adaptation time constants of inhibitory neurons
J_sfa_exc = [np.random.uniform(80, 1500)]   # adaptation strength: size of feedback kernel theta (= area under exponential) in mV*ms
J_sfa_inh = [np.random.uniform(80, 1500)]   # in mV*ms
tau_theta = np.array([tau_sfa_exc if prop == 1 else tau_sfa_inh for prop in pops_prop])
J_theta = np.array([J_sfa_exc if prop == 1 else J_sfa_inh for prop in pops_prop])

In [ ]:
print(J_syn)
print(mu)
print(tau_m)
print(V_th)
print(J_theta)
print(tau_theta)

print("-- -- --")

J_syn_list = J_syn.tolist()
mu_list = mu.tolist()
tau_m_list = tau_m.tolist()
V_th_list = V_th.tolist()
J_theta_list = J_theta.tolist()
tau_theta_list = tau_theta.tolist()

setting = 1
seed_num = 1

# Store your data into a dictionary
data_dict = {"setting": setting, 
        "seed_num": seed_num, 
        "J_syn": J_syn_list, 
        "mu": mu_list, 
        "tau_m": tau_m_list, 
        "V_th": V_th_list, 
        "J_theta": J_theta_list, 
        "tau_theta": tau_theta_list
        }

# Convert the dictionary into a JSON string
json_str = json.dumps(data_dict)

# Create the file name string
filename = f"data_{setting}-{seed_num}.json"

# Write the JSON string to a file
with open(filename, 'w') as json_file:
    json_file.write(json_str)


# Read the JSON string from the file
with open(filename, 'r') as json_file:
    json_str = json_file.read()

# Convert the JSON string into a dictionary
data_dict = json.loads(json_str)

# Convert the nested lists back into numpy arrays
J_syn = np.array(data_dict["J_syn"])
mu = np.array(data_dict["mu"])
tau_m = np.array(data_dict["tau_m"])
V_th = np.array(data_dict["V_th"])
J_theta = np.array(data_dict["J_theta"])
tau_theta = np.array(data_dict["tau_theta"])

print(J_syn)
print(mu)
print(tau_m)
print(V_th)
print(J_theta)
print(tau_theta)

print("-- -- --")

print(data_dict)

[[ 0.24724725 -0.          0.        ]
 [ 0.         -0.58247619  0.        ]
 [ 0.         -0.          0.1521292 ]]
[54.6528744  30.81797719 30.5206559 ]
[36.24766555 21.45326659 25.40004589]
[14.04083336 25.41295085 27.62235758]
[[1383.44940246]
 [ 447.57197117]
 [1383.44940246]]
[[ 942.37085234]
 [1077.55660579]
 [ 942.37085234]]
-- -- --
[[ 0.24724725 -0.          0.        ]
 [ 0.         -0.58247619  0.        ]
 [ 0.         -0.          0.1521292 ]]
[54.6528744  30.81797719 30.5206559 ]
[36.24766555 21.45326659 25.40004589]
[14.04083336 25.41295085 27.62235758]
[[1383.44940246]
 [ 447.57197117]
 [1383.44940246]]
[[ 942.37085234]
 [1077.55660579]
 [ 942.37085234]]
-- -- --
{'setting': 1, 'seed_num': 1, 'J_syn': [[0.24724724919346042, -0.0, 0.0], [0.0, -0.5824761916708973, 0.0], [0.0, -0.0, 0.15212919967157734]], 'mu': [54.65287439733692, 30.817977191412638, 30.520655897465833], 'tau_m': [36.247665546867466, 21.453266587341155, 25.40004588914421], 'V_th': [14.040833361554334, 25

## 3 pops parameter setting

In [ ]:
pops = np.array([400, 200, 400])
pops_prop = np.array([1, -1, 1]) # 1: excitatory, -1: inhibitory

pconn = np.array([[1, 1, 0],
          [1, 1, 1],
          [0, 1, 1]])
J = 0.0624  # excitatory synaptic weight in mV 
g = 0.496/0.0624   # inhibition-to-excitation ratio, -g*J is the weight for inhibitory signals
J_syn = np.outer(np.ones_like(pops_prop), np.where(pops_prop == -1, -g*J, J))
J_syn = J_syn * pconn

pconn_coeff = 1
pconn = pconn * pconn_coeff

mu = 36 * np.ones(len(pops)) # V_rest + I_external * R
tau_m = 20 * np.ones(len(pops))  # membrane time constant
V_th = 15. * np.ones(len(pops))  # baseline threshold (non-accumulating part)

tau_sfa_exc = [1000., 1000.]  # threshold adaptation time constants of excitatory neurons
tau_sfa_inh = [1000., 1000.]  # threshold adaptation time constants of inhibitory neurons
J_sfa_exc = [100., 1000.]   # adaptation strength: size of feedback kernel theta (= area under exponential) in mV*ms
J_sfa_inh = [100., 1000.]   # in mV*ms
tau_theta = np.array([tau_sfa_exc if prop == 1 else tau_sfa_inh for prop in pops_prop])
J_theta = np.array([J_sfa_exc if prop == 1 else J_sfa_inh for prop in pops_prop])

## Shuqi's para

In [ ]:
pops = np.array([400, 200, 400])
pops_prop = np.array([1, -1, 1]) # 1: excitatory, -1: inhibitory

pconn = np.array([[1, 1, 0],
          [1, 1, 1],
          [0, 1, 1]])
J = 0.096  # excitatory synaptic weight in mV
g = 0.384/0.096   # inhibition-to-excitation ratio, -g*J is the weight for inhibitory signals
J_syn = np.outer(np.ones_like(pops_prop), np.where(pops_prop == -1, -g*J, J))
J_syn = J_syn * pconn

pconn_coeff = 1.
pconn = pconn * pconn_coeff

mu = 36. * np.ones(len(pops)) # V_rest + I_external * R
tau_m = 20. * np.ones(len(pops))  # membrane time constant
V_th = 15. * np.ones(len(pops))  # baseline threshold (non-accumulating part)

tau_sfa_exc = [1000.]  # threshold adaptation time constants of excitatory neurons
tau_sfa_inh = [1000.]  # threshold adaptation time constants of inhibitory neurons
J_sfa_exc = [100.]   # adaptation strength: size of feedback kernel theta (= area under exponential) in mV*ms
J_sfa_inh = [100.]   # in mV*ms
tau_theta = np.array([tau_sfa_exc if prop == 1 else tau_sfa_inh for prop in pops_prop])
J_theta = np.array([J_sfa_exc if prop == 1 else J_sfa_inh for prop in pops_prop])

## original para

In [ ]:
pops = np.array([800, 200])
pops_prop = np.array([1, -1]) # 1: excitatory, -1: inhibitory

pconn = np.array([[1, 1],
          [1, 1]])
J = 0.3  # excitatory synaptic weight in mV 
g = 5   # inhibition-to-excitation ratio, -g*J is the weight for inhibitory signals
J_syn = np.outer(np.ones_like(pops_prop), np.where(pops_prop == -1, -g*J, J))
J_syn = J_syn * pconn

pconn_coeff = 0.2
pconn = pconn * pconn_coeff

mu = 24 * np.ones(len(pops)) # V_rest + I_external * R
tau_m = 20 * np.ones(len(pops))  # membrane time constant
V_th = 15. * np.ones(len(pops))  # baseline threshold (non-accumulating part)

tau_sfa_exc = [100., 1000.]  # threshold adaptation time constants of excitatory neurons
tau_sfa_inh = [100., 1000.]  # threshold adaptation time constants of inhibitory neurons
J_sfa_exc = [1000., 1000.]   # adaptation strength: size of feedback kernel theta (= area under exponential) in mV*ms
J_sfa_inh = [1000., 1000.]   # in mV*ms
tau_theta = np.array([tau_sfa_exc if prop == 1 else tau_sfa_inh for prop in pops_prop])
J_theta = np.array([J_sfa_exc if prop == 1 else J_sfa_inh for prop in pops_prop])

## other para

In [ ]:
pops = np.array([800, 200])
pops_prop = np.array([1, -1]) # 1: excitatory, -1: inhibitory

pconn = np.array([[1, 1],
          [1, 1]])
J = 0.3  # excitatory synaptic weight in mV, w^{αβ} in the paper
g = 5.   # inhibition-to-excitation ratio, -g*J is the weight for inhibitory signals
J_syn = np.outer(np.ones_like(pops_prop), np.where(pops_prop == -1, -g*J, J))
J_syn = J_syn * pconn

pconn_coeff = 0.2
pconn = pconn * pconn_coeff

mu = 24. * np.ones(len(pops)) # V_rest + I_external * R
tau_m = 20. * np.ones(len(pops))  # membrane time constant
V_th = 15. * np.ones(len(pops))  # baseline threshold (non-accumulating part)

tau_sfa_exc = [100., 1000.]  # threshold adaptation time constants of excitatory neurons
tau_sfa_inh = [100., 1000.]  # threshold adaptation time constants of inhibitory neurons
J_sfa_exc = [1000., 1000.]   # adaptation strength: size of feedback kernel theta (= area under exponential) in mV*ms
J_sfa_inh = [1000., 1000.]   # in mV*ms
tau_theta = np.array([tau_sfa_exc if prop == 1 else tau_sfa_inh for prop in pops_prop])
J_theta = np.array([J_sfa_exc if prop == 1 else J_sfa_inh for prop in pops_prop])

In [ ]:
pops = np.array([800, 200, 200])
pops_prop = np.array([1, -1, 1]) # 1: excitatory, -1: inhibitory

pconn = np.array([[1, 1, 1],
          [1, 1, 1],
          [1, 1, 1]])
J = 0.3  # excitatory synaptic weight in mV 
g = 5.   # inhibition-to-excitation ratio, -g*J is the weight for inhibitory signals
J_syn = np.outer(np.ones_like(pops_prop), np.where(pops_prop == -1, -g*J, J))
J_syn = J_syn * pconn

pconn_coeff = 0.2
pconn = pconn * pconn_coeff

mu = 24 * np.ones(len(pops)) # V_rest + I_external * R
tau_m = 20 * np.ones(len(pops))  # membrane time constant
V_th = 15. * np.ones(len(pops))  # baseline threshold (non-accumulating part)

tau_sfa_exc = [100., 1000.]  # threshold adaptation time constants of excitatory neurons
tau_sfa_inh = [100., 1000.]  # threshold adaptation time constants of inhibitory neurons
J_sfa_exc = [1000., 1000.]   # adaptation strength: size of feedback kernel theta (= area under exponential) in mV*ms
J_sfa_inh = [1000., 1000.]   # in mV*ms
tau_theta = np.array([tau_sfa_exc if prop == 1 else tau_sfa_inh for prop in pops_prop])
J_theta = np.array([J_sfa_exc if prop == 1 else J_sfa_inh for prop in pops_prop])